version: "3"
services:
  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: backend
    environment:
      API_BASE_URL: "http://localhost:8080"
      API_HTTP_HOST: "0.0.0.0"
      API_HTTP_PORT: "8080"
      API_HTTP_SCHEME: "http"
      DATABASE_URL: "postgres://admin:password@database:5432/database"
    ports:
      - "8080:8080"

  database:
    image: postgres:alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "admin", "-d", "database"]
      interval: 10s
      timeout: 60s
      retries: 3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
